package seonext

import (
	"github.com/version14/dot/internal/state"
	"github.com/version14/dot/pkg/dotapi"
)

type Generator struct{}

func New() *Generator { return &Generator{} }

func (g *Generator) Name() string    { return Manifest.Name }
func (g *Generator) Version() string { return Manifest.Version }

func (g *Generator) Generate(ctx *dotapi.Context) error {
	if err := ctx.State.UpdateJSON("package.json", func(d *state.JSONDoc) error {
		d.Merge(map[string]interface{}{
			"dependencies": map[string]interface{}{
				"next-seo": "^6.0.0",
			},
		})
		return nil
	}); err != nil {
		return err
	}

	ctx.State.WriteFile("src/lib/seo.config.ts", []byte(seoConfig), state.ContentRaw)
	ctx.State.WriteFile("src/components/SEO.tsx", []byte(seoTSX), state.ContentRaw)

	return nil
}

const seoConfig = `import type { DefaultSeoProps } from "next-seo";

export const defaultSEO: DefaultSeoProps = {
  defaultTitle: "My App",
  titleTemplate: "%s | My App",
  description: "Generated by dot",
  openGraph: {
    type: "website",
    locale: "en_US",
  },
};
`

const seoTSX = `import { NextSeo } from "next-seo";

interface SEOProps {
  title?: string;
  description?: string;
}

export function SEO({ title, description }: SEOProps) {
  return <NextSeo title={title} description={description} />;
}
`
