import type { DefaultSeoProps } from "next-seo";

export const defaultSEO: DefaultSeoProps = {
  defaultTitle: "My App",
  titleTemplate: "%s | My App",
  description: "Generated by dot",
  openGraph: {
    type: "website",
    locale: "en_US",
  },
};
