package nextjsbase

import (
	"fmt"

	"github.com/version14/dot/internal/state"
	"github.com/version14/dot/pkg/dotapi"
)

type Generator struct{}

func New() *Generator { return &Generator{} }

func (g *Generator) Name() string    { return Manifest.Name }
func (g *Generator) Version() string { return Manifest.Version }

func (g *Generator) Generate(ctx *dotapi.Context) error {
	projectName, _ := ctx.Answers["project_name"].(string)
	if projectName == "" {
		projectName = ctx.Spec.Metadata.ProjectName
	}
	if projectName == "" {
		projectName = "app"
	}

	if err := ctx.State.UpdateJSON("package.json", func(d *state.JSONDoc) error {
		d.Merge(map[string]interface{}{
			"scripts": map[string]interface{}{
				"dev":   "next dev --turbopack",
				"build": "next build",
				"start": "next start",
				"lint":  "next lint",
			},
			"dependencies": map[string]interface{}{
				"next":      "^15.0.0",
				"react":     "^19.0.0",
				"react-dom": "^19.0.0",
			},
			"devDependencies": map[string]interface{}{
				"@types/node":      "^22.0.0",
				"@types/react":     "^19.0.0",
				"@types/react-dom": "^19.0.0",
			},
		})
		return nil
	}); err != nil {
		return err
	}

	if err := ctx.State.UpdateJSON("tsconfig.json", func(d *state.JSONDoc) error {
		_ = d.SetNested("compilerOptions.jsx", "preserve")
		_ = d.SetNested("compilerOptions.lib", []interface{}{"DOM", "DOM.Iterable", "ES2022"})
		_ = d.SetNested("compilerOptions.plugins", []interface{}{map[string]interface{}{"name": "next"}})
		_ = d.SetNested("compilerOptions.paths", map[string]interface{}{"@/*": []interface{}{"./src/*"}})
		_ = d.SetNested("compilerOptions.allowJs", true)
		_ = d.SetNested("compilerOptions.noEmit", true)
		_ = d.SetNested("compilerOptions.incremental", true)
		_ = d.SetNested("compilerOptions.resolveJsonModule", true)
		_ = d.SetNested("compilerOptions.isolatedModules", true)
		_ = d.SetNested("exclude", []interface{}{"node_modules"})
		_ = d.SetNested("include", []interface{}{"src", ".next/types/**/*.ts"})
		return nil
	}); err != nil {
		return err
	}

	ctx.State.WriteFile("next.config.ts", []byte(nextConfig), state.ContentRaw)

	layoutContent := fmt.Sprintf(layoutTSX, projectName)
	ctx.State.WriteFile("src/app/layout.tsx", []byte(layoutContent), state.ContentRaw)

	pageContent := fmt.Sprintf(pageTSX, projectName)
	ctx.State.WriteFile("src/app/page.tsx", []byte(pageContent), state.ContentRaw)

	ctx.State.WriteFile("src/app/globals.css", []byte(globalCSS), state.ContentRaw)

	return nil
}

const nextConfig = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`

const layoutTSX = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "%s",
  description: "Generated by dot",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`

const pageTSX = `export default function Home() {
  return (
    <main>
      <h1>Hello from %s</h1>
    </main>
  );
}
`

const globalCSS = `*,
*::before,
*::after {
  box-sizing: border-box;
}

body {
  margin: 0;
}
`
